baseURL = 'http://localhost:1313/'
locale = 'ru'
defaultContentLanguage = 'ru'
title = 'Бэкап статей'
relativeURLs = true

[languages.ru]
  locale = 'ru'

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = 'tags'

[outputs]
  home = ["HTML"]
  section = ["HTML", "RSS"]

[services.rss]
  limit = 50
